apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
      version: 1.2
  replicas: 2 
  template:
    metadata:
      labels:
        app: hello-world
        version: 1.2
    spec:
      containers:
      - name: hello-world-pod
        image: arungupta/helloworld-spring-boot:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
